apiVersion: v1
kind: Service
metadata:
  name: adc-health
  namespace: adc-system
  labels:
    app: adc
    app.kubernetes.io/name: adc
    app.kubernetes.io/component: health
spec:
  selector:
    app: adc
  ports:
  - port: 8090
    targetPort: health
    protocol: TCP
    name: health
